# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes: 
      - ./pgdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'grammar'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
