# Use postgres/example user/password credentials
version: '3.9'

services:




  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes: 
      - ./pgdb:/var/lib/postgresql/data
    env_file:
      - .env
  
  web:
    image: grammar
    container_name: grammar
    build: .
    restart: always
    ports:
      - "8002:8000"
    links:
      - 'db'
    env_file:
      - .env
    depends_on:
      - 'db'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
